config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  get 'tasks/new', to: 'tasks#new'
  post 'tasks', to: 'tasks#create'

  get 'index', to: 'tasks#index'
  get 'tasks/:id', to: 'tasks#show', as: :task

  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit
  patch 'tasks/:id', to: 'tasks#update'

  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
    # creates an array with all the tasks
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to index_path(@task)
  end

  # GET /tasks/:id/edit
  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to index_path(@task)
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>

<%= form_with model: @task do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>
  <%= form.label :details %>
  <%= form.text_field :details %>
  <%= form.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1>YOOOOOOO!!!!!!! DO UR TA$K$</h1>
<ul>
  <% @tasks.each do |task| %>
    <li>
      <%# <%= task.title %>
      <%= link_to task.title, task_path(task.id) %>
    </li>
  <% end %>
</ul>
<p>
  <%= link_to "Add another ta$k", tasks_new_path %>
</p>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= form_with model: @task do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>
  <%= form.label :details %>
  <%= form.text_field :details %>
  <%= form.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1>These are ur ta$k details</h1>
<p>
  <%# display the task title and its details %>
  <%= @task.title %> ---
  <%= @task.details %>
</p>
<%= link_to "Back to ta$k$", index_path %>
<%= link_to "Edit ta$k", edit_path(@task.id) %>